version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - '${ADMINER_PORT}:8080'
    depends_on:
      - db

volumes:
  mysql-data:
